// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okoooexnwtkdebpkfsku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rb29vZXhud3RrZGVicGtmc2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODE5NzEsImV4cCI6MjA3MjQ1Nzk3MX0.iLE8HowrA3sgJAFfl4r0X9GEhj-jduXGYciF31k56Zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});